'use client';
import { useEffect, useState } from 'react';
import { getSupabaseClient } from '@/lib/supabase/client';
import * as React from 'react';

export default function SOSPage({ params }: { params: Promise<{ petId: string }> }) {
  const [pet, setPet] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  
  const { petId } = React.use(params);

  useEffect(() => {
    async function fetchPet() {
      const supabase = getSupabaseClient();
      
      const { data: petData } = await supabase
        .from('pets')
        .select('*')
        .eq('id', petId)
        .single();
      
      setPet(petData);
      setLoading(false);
    }
    
    fetchPet();
  }, [petId]);

  if (loading) {
    return <div className="text-center py-12">Loading emergency information...</div>;
  }
  
  if (!pet) {
    return (
      <div className="text-center py-12">
        <h1>❌ Pet Not Found</h1>
        <p>This emergency link is invalid.</p>
      </div>
    );
  }
  
  return (
    <div className="max-w-2xl mx-auto p-6">
      <div className="bg-red-500 text-white p-6 text-center rounded-t-2xl">
        <div className="text-5xl mb-2">🚨</div>
        <h1 className="text-2xl font-bold">EMERGENCY SOS</h1>
        <p>Important health information for {pet.name}</p>
      </div>
      
      <div className="bg-white p-6 border-x">
        <h2 className="text-xl font-bold text-center mb-4">{pet.name}</h2>
        <div className="space-y-3">
          <div className="flex justify-between border-b pb-2">
            <span className="font-semibold">Species:</span>
            <span>{pet.species || 'Not specified'}</span>
          </div>
          <div className="flex justify-between border-b pb-2">
            <span className="font-semibold">Breed:</span>
            <span>{pet.breed || 'Not specified'}</span>
          </div>
          <div className="flex justify-between border-b pb-2">
            <span className="font-semibold">Age:</span>
            <span>{pet.age || 'Not specified'} years</span>
          </div>
          <div className="flex justify-between border-b pb-2">
            <span className="font-semibold">Microchip:</span>
            <span>{pet.microchip || 'Not registered'}</span>
          </div>
        </div>
      </div>
      
      <div className="bg-gray-800 text-white p-4 text-center text-xs rounded-b-2xl">
        <p>Generated by VuraPet • Emergency SOS Card</p>
      </div>
    </div>
  );
}